#############################################################################
# Makefile for building: ichabod
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Nov 23 23:25:14 2012
# Project:  Ichabod.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Ichabod.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lrt -lQtWebKit -lQtScript -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		testview.cpp \
		testpage.cpp \
		cookiejar.cpp \
		network.cpp \
		factory.cpp \
		io.cpp \
		logger.cpp \
		downloader.cpp \
		browserdialog.cpp \
		tarrytown.cpp moc_testview.cpp \
		moc_testpage.cpp \
		moc_cookiejar.cpp \
		moc_network.cpp \
		moc_factory.cpp \
		moc_io.cpp \
		moc_logger.cpp \
		moc_downloader.cpp \
		moc_browserdialog.cpp \
		moc_tarrytown.cpp
OBJECTS       = main.o \
		testview.o \
		testpage.o \
		cookiejar.o \
		network.o \
		factory.o \
		io.o \
		logger.o \
		downloader.o \
		browserdialog.o \
		tarrytown.o \
		moc_testview.o \
		moc_testpage.o \
		moc_cookiejar.o \
		moc_network.o \
		moc_factory.o \
		moc_io.o \
		moc_logger.o \
		moc_downloader.o \
		moc_browserdialog.o \
		moc_tarrytown.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Ichabod.pro
QMAKE_TARGET  = ichabod
DESTDIR       = 
TARGET        = ichabod

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ichabod.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtWebKit.prl \
		/usr/lib/x86_64-linux-gnu/libQtScript.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Ichabod.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtWebKit.prl:
/usr/lib/x86_64-linux-gnu/libQtScript.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Ichabod.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ichabod1.0.0 || $(MKDIR) .tmp/ichabod1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ichabod1.0.0/ && $(COPY_FILE) --parents testview.h testpage.h cookiejar.h network.h factory.h io.h macros.h logger.h downloader.h browserdialog.h tarrytown.h getkeyevent.h .tmp/ichabod1.0.0/ && $(COPY_FILE) --parents main.cpp testview.cpp testpage.cpp cookiejar.cpp network.cpp factory.cpp io.cpp logger.cpp downloader.cpp browserdialog.cpp tarrytown.cpp .tmp/ichabod1.0.0/ && (cd `dirname .tmp/ichabod1.0.0` && $(TAR) ichabod1.0.0.tar ichabod1.0.0 && $(COMPRESS) ichabod1.0.0.tar) && $(MOVE) `dirname .tmp/ichabod1.0.0`/ichabod1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ichabod1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_testview.cpp moc_testpage.cpp moc_cookiejar.cpp moc_network.cpp moc_factory.cpp moc_io.cpp moc_logger.cpp moc_downloader.cpp moc_browserdialog.cpp moc_tarrytown.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_testview.cpp moc_testpage.cpp moc_cookiejar.cpp moc_network.cpp moc_factory.cpp moc_io.cpp moc_logger.cpp moc_downloader.cpp moc_browserdialog.cpp moc_tarrytown.cpp
moc_testview.cpp: testpage.h \
		downloader.h \
		logger.h \
		testview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) testview.h -o moc_testview.cpp

moc_testpage.cpp: downloader.h \
		testpage.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) testpage.h -o moc_testpage.cpp

moc_cookiejar.cpp: cookiejar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cookiejar.h -o moc_cookiejar.cpp

moc_network.cpp: logger.h \
		network.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) network.h -o moc_network.cpp

moc_factory.cpp: testview.h \
		testpage.h \
		downloader.h \
		logger.h \
		factory.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) factory.h -o moc_factory.cpp

moc_io.cpp: io.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) io.h -o moc_io.cpp

moc_logger.cpp: logger.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) logger.h -o moc_logger.cpp

moc_downloader.cpp: downloader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) downloader.h -o moc_downloader.cpp

moc_browserdialog.cpp: browserdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) browserdialog.h -o moc_browserdialog.cpp

moc_tarrytown.cpp: tarrytown.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tarrytown.h -o moc_tarrytown.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp factory.h \
		testview.h \
		testpage.h \
		downloader.h \
		logger.h \
		io.h \
		macros.h \
		browserdialog.h \
		tarrytown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

testview.o: testview.cpp testview.h \
		testpage.h \
		downloader.h \
		logger.h \
		network.h \
		cookiejar.h \
		browserdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testview.o testview.cpp

testpage.o: testpage.cpp testpage.h \
		downloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testpage.o testpage.cpp

cookiejar.o: cookiejar.cpp cookiejar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cookiejar.o cookiejar.cpp

network.o: network.cpp network.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

factory.o: factory.cpp factory.h \
		testview.h \
		testpage.h \
		downloader.h \
		logger.h \
		browserdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o factory.o factory.cpp

io.o: io.cpp io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io.o io.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

downloader.o: downloader.cpp downloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloader.o downloader.cpp

browserdialog.o: browserdialog.cpp browserdialog.h \
		testview.h \
		testpage.h \
		downloader.h \
		logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browserdialog.o browserdialog.cpp

tarrytown.o: tarrytown.cpp tarrytown.h \
		io.h \
		factory.h \
		testview.h \
		testpage.h \
		downloader.h \
		logger.h \
		getkeyevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tarrytown.o tarrytown.cpp

moc_testview.o: moc_testview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testview.o moc_testview.cpp

moc_testpage.o: moc_testpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testpage.o moc_testpage.cpp

moc_cookiejar.o: moc_cookiejar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cookiejar.o moc_cookiejar.cpp

moc_network.o: moc_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network.o moc_network.cpp

moc_factory.o: moc_factory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_factory.o moc_factory.cpp

moc_io.o: moc_io.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_io.o moc_io.cpp

moc_logger.o: moc_logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logger.o moc_logger.cpp

moc_downloader.o: moc_downloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloader.o moc_downloader.cpp

moc_browserdialog.o: moc_browserdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browserdialog.o moc_browserdialog.cpp

moc_tarrytown.o: moc_tarrytown.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tarrytown.o moc_tarrytown.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

