Document: ichabod
Title: Debian ichabod Manual
Author: <insert document author here>
Abstract: This manual describes what ichabod is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ichabod/ichabod.sgml.gz

Format: postscript
Files: /usr/share/doc/ichabod/ichabod.ps.gz

Format: text
Files: /usr/share/doc/ichabod/ichabod.text.gz

Format: HTML
Index: /usr/share/doc/ichabod/html/index.html
Files: /usr/share/doc/ichabod/html/*.html
